[package]
name = "oats-game-example"
version = "0.1.0"
edition = "2021"

[dependencies]
oats = { path = "../.." }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
rand = "0.8"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] } 